# Generated by Django 3.2.7 on 2021-10-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multiple',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
