# Generated by Django 3.2.7 on 2021-10-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
