# Generated by Django 3.2.7 on 2021-10-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiple',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
