# Generated by Django 3.2.7 on 2021-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211014_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_closed',
            field=models.BooleanField(default=True),
        ),
    ]
